name: Publish Coverage to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate coverage report
        run: npm run test:coverage:html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload coverage to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: coverage/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 
